= Закуска для размышлений
Михаил Забелин (travmaturg@gmail.com), CC BY-NC

https://travmaturg.github.io/text/snack_for_thought/


== О сущности бытия

Истинная разница в размере неприятностей - это разница между аварийным выходом и аварийным входом.

Задача: проинтегрировать всемирный пиздец по светлому будущему.

Ад - это когда бог не атеист.

Цель так же относится к смыслу, как средство к цели.

Жизнь без риска подобна навозу с консервантами.

Родители - это пыж судьбы.

Успеет ли эсхатология стать наукой?

Когда мёртвому закрывают глаза, ему помогают сделать facepalm.

С точки зрения дерева дятел вегетарианец.


== О природе человека

Людям свойственно не только ошибаться самим, но и вынуждать ошибаться других, чтобы учиться на их ошибках.

Когда детям говорят ``брось каку'', почему-то никогда не уточняют ``в кого''.

Люди делятся на две категории: одни не видят причин относиться к себе как к другим, а другие не видят причин относиться к себе иначе чем к другим.

Человек неисчерпаем как сортир.

Человек - это сумчатое животное с самодельной сумкой.


== О человечестве

Толпа вызывает у меня чувство, что в мою экологическую нишу пытаются установить писсуар.

Про человека в энциклопедии можно написать ``питается артефактами''.

Если бы Россия была родиной слонов, то ``мошной'' называли бы шапку.

Странно, что нигде нет традиции трижды стрелять через левое плечо.

Главная беда генофонда - не экология, а слишком поздние выкидыши.

Одна из причин терпеливости русских - раннее выявление тех, кто в пьяном виде не может обойтись без драки.

Заселять Марс нужно для того, чтобы сюда прилетели марсиане.

Феминистки делятся на борцов с исламом и фригидных лесбиянок.

Если феминисток брать в армию и направлять в горячие точки, они смогут совместить приятное с полезным - пострелять по мужикам.


== Государство

Дипломатия похожа на имитацию девственности после операции по смене пола.

Проблема не в том, что государство плохое, а в том, что при сегодняшнем населении это лучше чем ничего.

Армия - это школа такой жизни, которая мне не нужна.

Можно ли в графе ``национальность'' писать ``интернационалист''?

Военкомат должен оставить в покое тех, кто ``не мечтает стать генералом''.

Можно ли говорить про эффективность работы политика, если неизвестно, на кого он работает?

Юридическое: +
-Вы признаёте себя виновным? +
-Я не уверен, что этот вопрос имеет отношение к делу.

Предвыборная реклама предназначена исключительно для того, чтобы создать у народа иллюзию наличия выборов.

Самая неполиткорректная вещь - это зеркало. Странно, что зеркала ещё не запретили.

Почему регистрацию новорожденных (и перепись населения) не называют честно инвентаризацией?

Партии одной страны подобны ягодицам одной жопы: полный разрыв и полное единство требуют срочного хирургического вмешательства.

Демократическим государством достойно называться только такое, которое согласно на всемирный референдум по поводу своего суверенитета.

Политкорректность - это недержание прав человека.

Родина там, где ``государство лезет со своим уставом в мой монастырь''. А где наоборот ``dura lex'' - там уже чужая страна.

Государство - это высшая форма корпоративного солипсизма. Поэтому государство стремится уничтожить всё, что не в компетенции государства. Примерами могут быть криптография, самогонные аппараты и всемирный интернет (не путать с государственными локалками типа китайской и северокорейской). Также государство любой ценой будет ликвидировать негосударственную родину, чтобы осталась только родина через государство.

Лучше всеобщая слежка, чем монополия на слежку.

Про министерство культуры: для меня представляет ценность только та часть культуры, которая не в компетенции никакого министерства.

Можно ли назвать анархизмом позицию ``я за то, чтобы государство было чем заменить''?

Государство - это богатый источник омонимов, например ``закон'', ``служба'' и ``долг''.

``якобы в интересах ребёнка, а на самом деле в интересах другого ребёнка''

Считать гейпарады уважительной причиной для цензуры могут только пидорасы в плохом смысле.

``какая страна, такой и рейх''

Отказываться от открытого голосования из-за возможности принуждения - это как отказываться от денег из-за существования гопников.

Моё отношение к усыновлению однополыми парами: нужно приравнять их возможности к усыновлению одинокими людьми.

Если государство хочет продемонстрировать свою способность создать хоть что-то серьёзное не через жопу - пусть создаст мобильного оператора, который не наёбывает.

Штифтованый ствол - это аналог петушиной посуды.

Когда размножение называют государственным делом - размножаются в основном те, у кого не хватает мозгов отличить своё дело от государственного.

Оружие делится на своё и казённое, все остальные классификации основаны на второстепенных деталях.

Когда государство сравнивает себя с родителями - это ещё хуже, чем когда оно называет себя родиной.

Когда государство называет что-то собственностью, оно говорит про возможность это отнимать.


=== Фашизм

Фашизм - это когда государство не понимает, что такое ``лезть не в своё дело''.

Один древнегреческий философ сказал, что человек - это мера всех вещей. Фашисты считают, что государство - это мера всех вещей.

Фашизм - это приапизм вертикали власти.

Фашизм - это диктатура государства.

Фашизм - это когда человек для государства, а не государство для человека.

Про китайский ``социальный кредит'': кто называет государственный рейтинг социальным - тот фашист.

Фашизм - это когда государство ошибочно считает, что у него монополия на коллективную деятельность людей.

Фашизм - это когда не видят разницы между страной и государством. Или хотят, чтобы от страны осталось только государство.

Кто знает и отрицает разницу между легальностью и легитимностью - тот фашист.

Фашизм - это монополия государства на родину.


=== Церковь

Бога придумали первобытные паханы, чтобы не выглядеть самозванцами.

Миссионеры - это культурные метастазы.

Государства не стремятся избавиться от религий, потому что неверующий народ overqualified.

Церковь считает себя *необходимым* посредником между богом и простыми смертными. Насколько я понимаю, это богохульство и грех гордыни.

Нимб - это символ обрезания.

Любая церковь называет душой нечто такое, что имеет отношение именно к этой церкви. В рамках этой терминологии считаю необходимым заявить, что у меня нет души.

Свобода вероисповедания не может быть дарована государством, она может быть только собственная. Законы о свободе вероисповедания - это попытка государства приписать себе чужие заслуги.

``это не личность, это раб божий''

Христианство - это карательный психоанализ.


=== Экономика

Про оптимизацию налогов: торговаться с вымогателями - это БДСМ.

Следующая экономическая революция в США - ликвидация покупок не в кредит.

Налоги - это когда государство считает мои деньги недополученой прибылью.

Инфляция - это медленный дефолт. Главная проблема - в какой валюте измерять инфляцию.

Деньги - это одноразовый документ.


== Патенты

Патенты - это религия. Её сторонники верят в то, что особым образом оформленный кусок бумаги может избирательно ослабить умственные способности всех людей.

Патент - это некий договор патентовладельца с государством. Каким образом он может к чему-то обязывать тех, кто в нём не участвует?

Патенты несовместимы с презумпцией невиновности (для нарушения патента его не требуется _de facto_ использовать), поэтому сторонники патентов - это террористы и педофилы.

Описывать защиту монополии в терминах плагиата - такое же введение лишних сущностей, как и описывать светофор в терминах права собственности на кусок дороги. Кстати, светофор должен переключаться, иначе он сломан.

Патент является не свойством запатентованой вещи, а всего лишь свойством патентной системы. То есть патентная система - это ещё один пример корпоративного солипсизма.

Отрицание авторства независимых изобретателей - это _de facto_ плагиат. Таким образом, любой патентовладелец автоматически является плагиатором (даже если он тоже автор, что иногда бывает).


== Латентная шизография

бессмердие

крантовщик

начхальник

жpатвопpиношение

эрзац-капут

``все что нажито непосильным трудом за бесцельно прожитые годы''

полноценная скидка

палеоонтология

...послал туда, откуда ноги растут

Евангелие от кутюр

для углубления кругозора

внебрачное дитя природы

боеприпастбище

парфюмерзость

вездец

PayStation

царь-памятник

замечтательно

``... всё равно что считать глистов теплокровными''

неувядающее болото

-Фильтруй базар! +
-Фильтр засорился.

демпинг бесценного

двухкомнатный санузел

хтоническое терраформирование

акромегалиты

шанкреатит

-работа не волк, - сказал ветеринар и взял ружьё

стилизация под подделку

``блеск и нищета гламура''

лжепарадокс

псевдогаллюцинация

гомеопатический перфекционизм

латентный ниндзя

солипсист-эксгибиционист

трудиться в поте юридического лица

буддильник

секвестр головного мозга

нефритовые нунчаки

фамилия "Гешефтберг" (надеюсь, на практике не применялалсь)

Carnivorkuta

президец

рассолнечное утро

дохуящик

Про что криптограф может сказать ``соль земли''?

продолбоватый

``они мне не элита''

оскорблендер

колебёдка

копрограмма

клоунирование

шкафандр

прирождённый выродок

трофейная идеология

циссексуалист

изувековечить

embarrassador

философрения

декапитан

мобильный обиратор

обфигняемый


== Изобретения, серьёзные и наоборот

Тесты на знание русского языка: +
Отличить вспотевшего человека от запотевшего. +
Какой навоз более качественный, говняный или говённый? +
Кто страшнее, клоун-стоматолог или стоматолог-клоун? +
Чем отличаются ``казённый публичный дом'' и ``публичный казённый дом''? +
Какая ситуация более постоянная, ``насрано'' или ``засрано''? +
Какое из слов ``раздолбил'', ``раздолбал'' и ``задолбал'' описывает ваше отношение к этому экзамену?

Газированый рассол.

Сувенирный штопор с левой резьбой.

Сериал о съёмках сериала.

Способ проведения выборов: +
Каждому варианту ставить оценку - ``годен'', ``не годен'' или ``воздержался''. На второй тур пропускать тех, у кого неотрицательная разница между ``годен'' и ``не годен'', а там по максимальной разности (а если останется один вариант или ни одного - это соответственно выборы в один тур или несостоявшиеся выборы). +
Примечание 1: +
На практике варианты делятся на ``хочу их победы'', ``только не это'' и ``все остальные''. Вариант ``воздержался'' даёт возможность выразить такое мнение без числовых оценок. Если нужно упростить - лучше отказаться от второго тура. +
Примечание 2: +
Можно разделить ``воздержался'' на ``нейтральная оценка'' и ``не знаю''. Тогда вместо (``годен''-``не годен'') будет (``годен''-``не годен'')/(всё кроме ``не знаю'').

Дирижёрские нунчаки.

Зубная паста с глутаматом натрия.

Резервация для верующих.

Для создания плотной атмосферы на Марсе там нужно разбудить вулканы (тут могут помочь астероиды/кометы в нужных местах, но их внутренних веществ не хватит, нужно именно раскрытие местных ресурсов).

Посадить шаттл на остров Пасхи, чтобы будущие археологи считали его транспортом для статуй.

Самое эффективное правило дорожного движение для пешеходов - вести себя так, как будто водители тебя не видят.

Одна из возможных причин вымирания динозавров: в результате оползней и землетрясений резко изменилась карта течений.

Шнобелевская премия Дарвина

Возможный механизм всемирного потопа: метеорит падает в удачную точку Антарктиды и много льда сползает в океан.

Гипотеза: суп - это рудимент фильтрации еды через жабры.

На сигаретах должно быть написано ``вредно для здоровья **окружающих**''.

HDD с двумя половинными наборами головок: с одной стороны для верхних поверхностей, с другой для нижних. Так можно уменьшить расстояние между пластинами. Если пластины тоньше расстояния между пластинами, тогда можно крайние пластины использовать только с внутренних сторон. (с двумя полными наборами уже были)

Причиной каких-то душевных состояний может быть химеризм мозга.


=== Оружие

Глушители уменьшенной длины, которые можно прикручивать несколько штук подряд.

Мина-ловушка в виде инертного боеприпаса.

Телескопический глушитель.

Прицельная сетка в виде пацифика.

Совместить трассер с газогенератором.


=== Физика

Гравитационная самофокусировка света в вакууме.

Кварки - это развилки на струнах. +
Отсюда следует: +
1. Выход более трёх струн из одной точки можно бесконечно малым шевелением преобразовать в обычные развилки, а от них уже так просто не избавиться. Таким образом, число 3 оказывается важным, и это может быть связано с электрическим зарядом, кратным e/3. +
2. Кварки не могут появляться по одной штуке.

Тёмная материя - это медленные нейтрино. Кстати, по их распределению в гравитационном поле галактик можно оценить распределение скоростей.

Разнообразный химический состав комет, астероидов и космической пыли связан с тем, что перед взрывом звезды там слои с разным составом и они не успевают полностью перемешаться.

Альтернативный способ образования звёзд: +
Сначала появляются несколько объектов типа Юпитера, потом при столкновениях постепенно набирается достаточная масса (речь не идёт про миллиарды лет, просто кривое облако схлопнулось не сразу в один шарик). Некоторые объекты могут улететь или стать планетами этой звезды, тут уже лотерея. Кстати, такая ситуация облегчает появление двойных звёзд.

Инфляция и большой разрыв - это один и тот же процесс.

Эксперимент: при интерференции единичной заряженной частицы будет ли отталкивание от себя?


== Надписи и названия

В операционной: ``Разделяй и властвуй''.

В столовой: ``Третьего не дано''.

Краска для волос ``На все 100''.

Порнофильм ``На самом интересном месте''.

Фильм ``Особенности национального национального вопроса''.

В туалете: ``Кто может - пусть сделает лучше''.

Оптический прицел ``Некpоскоп''.

В кабинете врача: ``Раньше надо было стесняться''.

На пункте приёма макулатуры: ``Рукописи не горят''.

``God created me in his own image and all I got was this loosy T-shirt''.

Огнетушитель ``Феникс''.

Наушники ``Превед''.

Тест на беременность ``Зачёт''.

Ресторан ``Очаг зоопедофага''.

Капитан Product Placement


== Подражание классике

Редкий бумеранг долетит до середины Днепра.

Зачёты по осени считают.

Глядя на мир, нельзя не издеваться.

Кто не кормит свою армию - будет кормить государственную.

Белеет череп одинокий, +
в затылке проткнут долотом. +
Откуда он в стране далёкой? +
Что сделал он в краю родном?

На два унитаза сядешь - ни в один не попадёшь.

Плох тот философ, который не мечтает покончить с собой.

Жопа на глиняных ногах.

Путь к сердцу мужчин разной ориентации лежит через разные части пищеварительной системы.

Пиздец в России - больше, чем пиздец.

Чужая душа - потёмкинская деревня.

А ты не путай свой личный контент с издательским!

Государство таки сделает меня анархистом.

Если человек гэбист, то это надолго.

монополия на терроризм

-Что произошло с Конституцией? +
-Она утонула.

пули бы делать из этих гвоздей


== Компьютеры и электроника

Идея: в машине Тьюринга проинициализировать ленту чем-нибудь алгоритмически неразрешимым.

Основное достоинство командной строки - отсутствие метафор, а мощность языка на втором месте.

Модификафия теста Тьюринга: компьютер должен отличить компьютер от человека.

Адресация по байтам объединяет недостатки адресации по битам и по регистрам.

Должна быть связь между стилем работы с браузером и отношением к языкам программирования. Открытие страницы можно сравнить с вызовом функции, а дальше идут аналогии со стеком, параллельностью и даже continuation passing style. Подозреваю, что сторонники декларативных языков реже используют кнопку back.

C++ - это макроассемблер с манией величия. (важный симптом: семантика описывается через реализацию)

Настоящий модератор даже на кладбище видит плюсы.

Странно, что в UNIX'е есть /home, но нет /etc/home и /var/home.

Free as in ``гусары денег не берут''.

Социальная сеть ``Гранфаллон''.

Haskell похож на одноколёсный велосипед.

Гипотеза: аватары во всяких форумах/блогах/комментариях - это имитация говорящих голов из комиксов.

Любой достаточно продвинутый форум содержит в себе хреновую имитацию половины NNTP/Usenet.

Нормальная документация - это когда нет необходимости заглядывать в код.

До этого Столлман ещё не додумался: Microsoft развивает Haskell, чтобы внедрить монадический DRM в качестве новояза (то есть убрать просто информацию и оставить только информацию с правообладателем).

Secure Boot нейтрализует аргумент ``не нравится - не используй'' и тем самым даёт моральное основание использовать ZverDVD.

Символом значительной части программирования должна быть Эйфелева башня, потому что это фрактальный костыль.

Emacs и TeX похожи: там есть компактное ядро, но традиционный комплект поставки является большой помойкой.

Для /tmp идеально подойдёт ФС, которая форматируется за секунду.

Vim плохо влияет на карьеру, потому что многие оценивают продуктивность по износу клавиатуры.

Open space повышает продуктивность начальства ценой продуктивности остальных.

Стандартную библиотеку C давно пора перенести в POSIX, а в языке оставить только язык. +
1. На практике используют или POSIX, или особенности компилятора. +
2. Это упростит совместимость с C++.

Если бы строителям ставили задачи как программистам: +
Сначала сделай один угол крыши, а потом оставшиеся части крыши.

Програмно-аппаратные комплексы являются мошенничеством, потому что у продавца нет права передавать софт в собственность покупателю.

Изобретение пробела - это великий_шаг_в_развитии_письменности. Отказ от разделителей УстарелНаНесколькоТысячЛет.

Браузеры стали похожи на офисные пакеты: для своих документов такие монстры не нужны, но их приходится держать для чужих документов.

Шифрование добавляет кучу способов самому всё потерять, поэтому шифровать нужно только то, что лучше потерять самому, чем показать посторонним.

По логике некоторых работодателей, повар не может дома готовить.

Ещё про шифрование: необходимо различать вопросы ``от кого защищаемся'' и ``насколько серьёзная защита''. Например, возможно сочетание ``главный враг - государство'' и ``аналог поднятого стекла в припаркованой машине''.

Если бы я делал нейронную сеть: +
В слое 0 входные данные, в слое n результат вычисления, в слоях 1..n-1 по одному нейрону. +
Каждый слой зависит от всех предыдущих слоёв.


=== DRM

Про DRM: если товар не перешёл в собственность покупателя - продавец является мошенником.

DRM является трояном, потому что он стремиться контролировать *всю* систему, а не только свой родной продукт. Кстати, именно поэтому модель ``всегда онлайн'' является меньшим злом.

Произведение с издательскими ватермарками является подделкой. Произведение с авторскими ватермарками является говном.

DRM является цензурой, потому что он предназначен для ликвидации неиздательского контента. Опять корпоративный солипсизм.


== Парашютизм

Не так страшен парашют, как его запаска.

Однажды в суровую летнюю пору +
я из двери вышел - был сильный поток; +
гляжу - возвышается купол огромный, +
несущий меня как картошки мешок.

К вопросу о ненормальности парашютистов: нормальные люди сначала пьянствуют, а потом безобразия нарушают. Парашютисты делают наоборот.

``...размахивая вестибулярным аппаратом''

Свуперы подобно программистам считают, что в километре 1024 метра.

Идея: сайпрес на софтлинки + транзит.


== Мудрофилия

Лекция по философии похожа на экскурсию в психушку.

Лучшая тренировка для философа - заглянуть в психушку и там каждого опровергать.

Философ - это тот, кто не понимает, что он не понимает философию.

-Чем занимается философия? +
-Чем хочет, тем и занимается.

Пример диалектики - сравнительный статус логического следования и причинно-следственной связи. Они эквивалентны логически, но не причинно-следственно.

Ничто - это наше всё.

На экзаменах по философии спрашивают только зубрёжку, потому что иначе можно ответить ``ты сам-то понял, что спросил?''.

Один из самый эффективных способов не отвечать на вопрос - назвать этот вопрос философским. Но этот способ не работает на экзамене по философии.

Если математика - это гимнастика для ума, то философия - это вывих. Психическое заболевание - это разрыв связок. Религия - это неправильно сросшийся перелом.

Когда я слушал преподавателя философии, меня не покидало ощущение, что у одного из нас проблемы с головой.

Язык философии - пример того, что попытки гуманитариев что-то формализовать обычно приводят к ритуализованному замороченному словоблудию. Философия нуждается в бурбакизме для совершения торжественного апоптоза.

Большинство философских вопросов - замаскированные терминологические, т. е. для ответа на них достаточно договориться об определениях всех использованных в вопросе слов.

Курс философии - это опыт общения с лженаукой.

Философия имеет такое же отношение к науке, как алхимия к химии и обезьяна к человеку.

Если философ употребляет слово ``парадокс'' - он имеет в виду задачу, с которой здравый смысл справился лучше философии.

Если кто-то назовёт философию наукой - в ответ необходимо потребовать обосновать существование философии.

Философские теории противоречивы как беременный солипсист.

Название статьи: ``Death considered harmful''.

-Жить хорошо. +
-О вкусах не спорят.

Философию нужно переименовать: она давно превратилась из любви к мудрости в карго-мудрость.

Философия - это дискурсивный дискурс.

Глюк - это эксклюзивная концепция.

Античная педагогика - это ректальная гносеология. (Ректотермальный криптоанализ тоже можно так назвать. К чему бы это?)


=== Солипсизм

Чем отличаются солипсист-идеалист и солипсист-материалист?

Как правильно: ``объективный солипсизм'' или ``субъективный солипсизм''?

Солипсизм - это субъективный материализм.

Солипсизм - это экзистенциальный фатализм.

Чем отличаются солипсист-интроверт и солипсист-экстраверт?


== Мозговедение

Мудрец - это тот, кто сам себя правильно понимает. Или понимает, что не понимает.

Чем больше мозг, тем глубже он заблуждается.

Мыслящим существом является только тот, кто считает свои мнения в разной степени объективными.

Основная человеческая ошибка - неправильная постановка вопроса.

К религии склонны те, кто согласен на бессмертие.

Чем меньше совесть - тем больше на ней помещается.

Извилины в голове мешают выковыривать оттуда дерьмо.

К сожалению, многие понимают в меру *чужой* испорченности...

Если человек без царя в голове - он ищет себе другого царя.

Основная сложность психологии - отсутствие четкой границы между добровольными и принудительными действиями.

Когда говорят "антиобщественный", очень редко уточняют, а каком обществе идёт речь.

Люди делятся на две категории: одни предпочитают работать одновременно с разговорами, а другие в свободное от разговоров время.

Странно, что этнография не считается разделом психиатрии.

Психиатрия - это экспериментальная философия.

Не исключено, что раздвоение личности - это просто бифуркация ``выгодного'' психического состояния.

Странно, что в человеческих языках для мужского/женского рода (которые вообще не нужны) и единственного/множественного числа нет варианта ``неизвестно или не имеет значения'' (стоит ли их различать - отдельный вопрос), который при наличии проектирования был бы по умолчанию. Похоже, что это связано с проблемами обучения в детском возрасте.

Мыслителя можно распознать по реакции на отзыв ``он сам не понимает, насколько прав'': он сочтёт это комплиментом, а ламер начнёт возмущаться ``это Я не понимаю?!''.

Самый страшный человек - это мазохист, которого мучает совесть.

Говорят, что дети часто заимствуют у родителей мнения/вкусы/мировоззрение. Но может оказаться, что они просто используют некоторые слова в одинаковых необщепринятых значениях.

У мозговедов большие сложности с развитыми мозгами. Во-первых, психическое состояние не связано напрямую с действиями/словами. Во-вторых, есть шансы контролировать ситуацию при сравнительно сильных нарушениях.

Если попытаться разговаривать с каждым на его персональном диалекте - обязательно неправильно процитируют и обзовут лжецом.

Паранойя - это когда кто-то перестаёт надеяться на то, что он Неуловимый Джо.

Религия - это неспособность признать, что несамозванцев не бывает.


=== Психоанализ

Иногда ``оговорки по Фрейду'' находятся в головах слушателей.

Психоанализ - это вербальная уринотерапия.

Психоанализ - это церебральный фистинг.


== Половая жизнь человеческого мозга

Первое, что сделал человек - догадался метить территорию прямо на собственном теле.

Значительная часть беспочвенной стрельбы - это попытка метить территорию свинцом. И вообще людям свойственно метить территорию чем-нибудь по сути не своим.

Про некоторых женщин: я не могу назвать человека богатым, если он не может себе позволить удобную обувь.

Давно пора ввести термины ``традиционное извращение'' и ``нетрадиционное извращение''.

Отличие эротики от порнографии: эротика предназначена для любителей смотреть на женское тело, а порнография для любителей смотреть на чужой хуй.

Метросексуал - это пассивный визажист.

Онанизм биологически нормален ровно до тех пор, пока не является ориентацией. Не понимаю, о чём тут копья ломали.

Главное отличие транссексуала от извращенца: транссексуал удаляет яйца/яичники (иначе при чём тут смена пола?), а извращенец сохраняет.


== Звуколожество

Концерт в толпе похож на мангал в сортире.

У аудиофильской акустики частотная характеристика кривая как зеркало телескопа.

Подбор наушников под музыкальный жанр подобен подбору термоса под температуру содержимого.

Наушники делятся на студийные, китайские и из тазобедренного сустава девственницы.

Про ``тёплый ламповый звук'': акустика делится на честную и для хуёвых записей.

Вкусовщина и ``концепция звука'' за пределами диска/файла - это брак.

``Интересные наушники'' - это такой же бред, как и ``вкусная посуда''. Посуда делится на чистую и грязную, а наушники на точные и неточные.

Концертная запись объединяет в себе плохой звук и отсутствие личного участия.


== Алкоголь

Юристы напрасно считают, что всяческое опьянение как-то связано с тяжестью преступления. Важно другое: было ли преступление адресное или против первого встречного.

Безалкогольное пиво подобно обезжиренному вазелину.

Цирроз - это мозолистая печень.

У повышенного гемоглобина есть один недостаток: из-за менее активного дыхания замедляется выведение последствий пьянки через лёгкие.

Почему-то людям не приходит в голову, что креплёные напитки - это *разбавленые* напитки.

Массовое пьянство способствует отбору людей с сильной печенью, а сильная печень помогает женщинам выдержать беременность.

Продажу алкоголя нужно разрешить с того возраста, когда в школе проходят разницу между этанолом и метанолом.


== Разное

Питеpская погода: Солнце светит как из ведра.

Комок в горле - это когда очко сжалось по самые гланды.

Единственное оправдание метанию бисера перед свиньями - попытка не потерять квалификацию.

Самый важный шаг в эволюции любых мыслящих существ - это перемещение сексуальных действий из рефлекторных в инстинктивные.

Лучше быть непонятым, чем понятым неправильно.

Можно ли клизму считать инвестицией?

Танк - это трактор-берсерк.

-... потряс мир!!! +
-Какое мне дело до того мира, который он потряс?

Питерский климат - мечта хирурга: бестеневое освещение в любое время года.

Кто метит территорию, тот тем самым демонстрирует, что его территория у параши.

Было бы интересно набрать статистику по непереносимости вида крови разнообразными дальтониками.

Я не удивлюсь, если при жизни моего поколения выражение ``режиссёрская версия фильма'' начнёт означать ``без рекламных пауз''.

Если собака вместо своей территории метит человеческую - в это надо ткнуть мордой её хозяина.

Любовь к рекламе, моде и геральдике - это пассивный фетишизм.

Неправильно говорить, что война стимулирует развитие науки и техники. Во время войны всего лишь перестают посылать тех, кто не нуждается в военной мотивации.

Увеличенные мускулы культуристов имеют такое же отношение к здоровью, как и увеличенная печень алкоголиков.

Если кажется, что в какой-то области всё уже придумано - нужно попробовать создать классификацию ошибок.

Историки - это некросплетники.

Признаком победы глобализации будет всемирная унификация армейских боеприпасов.

Не понимаю, как можно называть культурной столицей город, который засран рекламой.

Разница между писателем и графоманом - примерно как между драчуном и эпилептиком.

Нормальная кучность - это когда использованной мишенью можно подтереться.

Следующий шаг эволюции после появления разума - ликвидация импритинга.

Если кто-нибудь матерится - это может оказаться проявлением вежливости, а не грубости. Во многих случаях принято отвечать на том же языке, на котором обратились.

``такие деньги невозможно потратить, их можно только проебать''

Урбанизация - это когда владелец машины покупает проездной.

Употребление символа ``TM'' обычно говорит о каше в голове: торговой маркой является только название, но не называемая вещь.

Шахматы - это церебральный культуризм.

Пилинг - это гомеопатическая кремация.

Рыночная экономика - это когда любой качественный товар называют профессиональным.

Удаление зуба - это гомеопатическая декапитация.

Культура - это то, что не забыли к моменту перехода в public domain.

Гипотезы о внеземной жизни: +
Пригодные для жизни места как правило очень локальные (типа вулкана под ледником) и сложные организмы там в принципе не могут развиться. +
У обитаемых планет обычно соседние планеты непригодны для заселения (или отсутствуют), а без такой тренировки мало шансов успешно отправить поселенцев к другим звёздам (и большинство не пытается). +
Тектоника плит бывает редко, а без неё недостаточно легкодоступных минералов для технологической/промышленной цивилизации. Из камней и палок можно сделать сельское хозяйство, но не космическую программу.

Цивилизация - это паразитирование мозга/разума на обычной биологии. +
Главная опасность: паразиты обычно становятся примитивными.

Самовыражение - это когда как я хочу, а не как заказчик хочет.

M16 дымит где питается, потому что у конструктора наркоманская фамилия.

У галстука две функции: корпоративный фетишизм и нарушение кровоснабжения мозга.

Сохранение телефонного номера при смене оператора - это такой же бред, как и сохранение почтового адреса при переезде.

Реклама и прочая пропаганда - это поддельный дискурс.

Незваный редактор хуже цензора.

Почему считать с 1 начали раньше, чем с 0: +
Есть разные понятия: номер элемента, количество уже посчитаных элементов и общее количество элементов. +
В бытовых ситуациях интересует в первую очередь общее количество элементов, и при его вычислении естественным образом возникает количество уже посчитаных элементов. Номер элемента нужен только для различения элементов, а для этой задачи подходит количество уже посчитаных элементов. +
В математике и программировании роль номера элемента намного важнее, и там это уже отдельное понятие. Пример: умножение многочленов.

Маркетинг головного мозга - это когда любую продажу считают результатом рекламы. На практике это приводит к невозможности купить товар, пока его не прорекламируют.

Cover letter - это такое же извращение, как и на диск с фильмом добавлять трейлер этого фильма.

Медвежья болезнь - это адиабатический катарсис.

Идеальная карьера - это когда достаточно денег, чтобы не работать.

Фараонов начали бальзамировать, потому что пирамиды не успевали построить и тело нужно было как-то сохранить.

Флаг - это логотип на палке.

