#!/bin/sh

f=/files/travmaturg
bf=/big_files/travmaturg

l="ln -s -T"

#mkdir -p $f/my/private
#$l $f/my/private/ssh ~/.ssh

$l /media ~/0_media
$l /usr/share/doc ~/0_doc

tmp=/var/tmp/travmaturg
mkdir -p $tmp
$l $tmp ~/0_tmp

download=$bf/download
mkdir -p $download
$l $download ~/0_download

torrent=$bf/torrent
mkdir -p $torrent
$l $torrent ~/0_torrent

$l $f/archive ~/0_archive
$l $f/my ~/0_my
$l $f/public ~/0_public
$l $f/raw_samples ~/0_raw_samples

$l $bf/porn ~/0_porn
$l $bf/public_extra ~/0_public_extra
$l $bf/unsorted ~/0_unsorted


