#!/bin/sh


#install="aptitude --without-recommends install"
install="apt-get --no-install-recommends --ignore-missing --show-progress install"


autotools="autoconf automake libtool"
#gtk="libgtk-3-dev"
qt="libqt4-dev qt5-qmake qtbase5-dev qttools5-dev-tools"
#sdl="libsdl2-dev libsdl2-mixer-dev libsdl2-net-dev"
common_dev="$autotools build-essential cmake pkg-config $qt"
# libglib2.0-dev $gtk libpango1.0-dev $sdl

c_cpp="gcc g++"
check="cppcheck splint"
git="git git-doc gitk git-gui"
scheme="racket racket-doc"
tiff="libtiff-dev libtiff-doc"
my_dev="$c_cpp $check $git make manpages-dev libpng-dev $scheme $tiff"

#freeciv="libatk1.0-dev libcurl-dev libgdk-pixbuf2.0-dev libicu-dev liblua5.4-dev"
# glib gtk pango pkg-config sdl

unetbootin="mtools syslinux"
# qt

dev="$common_dev $my_dev $unetbootin"
# $freeciv


download="wget yt-dlp"
#sylpheed="sylpheed bsfilter"
net="liferea qbittorrent tor $download"
# $sylpheed

dict_en_ru="dict-freedict-eng-rus mueller7-dict"
dict_comp="dict-foldoc dict-jargon dict-vera"
dict_list="$dict_en_ru $dict_comp dict-elements dict-gcide dict-wn"
dict="dict dictd $dict_list"
diff="kdiff3 kdiff3-doc meld"
view="qpdfview xpdf gv djview4"
tex="texlive texlive-lang-cyrillic texlive-htmlxml"
vim="vim-gtk3 vim-doc"
text="$dict $diff $view $tex $vim asciidoc pandoc"

space="gdmap qdirstat ncdu fslint fdupes"
archives="zip unzip unar p7zip"
files="$space $archives mc rsync"
disk="gparted gsmartcontrol"
encfs="encfs libpam-encfs"
apt="apt-doc aptitude aptitude-doc-en"
debian="debtree apt-transport-tor $apt"
# debmirror
system="$files $disk $debian $encfs htop shellcheck"

images="geeqie rawtherapee hugin"
cue="cuetools shntool flac"
players="audacious $cue vlc"
other="$images $players alsa-utils"


pkg_list="$dev $net $text $system $other"


$install $pkg_list

